# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:   ^/(login$|register|resetting)
            anonymous: true
        main:
            pattern: ^/.*
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   fos_user_security_logout
                target: _challenge_front_produit_list
            anonymous: true
#            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/(login$|register|resetting), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/front/commande, roles: ROLE_USER }
        - { path: ^/front/panier, roles: ROLE_USER }
        - { path: ^/front.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back.*, roles: ROLE_USER }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }